import sqlite3
import aiosqlite
import aiofiles
import json
from datetime import datetime
import os
import asyncio
import time

class ServerDB:
    def __init__(self, db_path="server.db"):
        self.db_path = db_path
        self._write_lock = asyncio.Lock()
        try:
            self.agent_offline_after_seconds = int(os.environ.get("AGENT_OFFLINE_AFTER_SECONDS", "300"))
        except ValueError:
            self.agent_offline_after_seconds = 300
        # Keep initial table creation synchronous to ensure DB exists at startup
        self._init_db_sync()

    def _init_db_sync(self):
        """Synchronous initialization for application startup"""
        # Use a generous timeout: another process (e.g. an upgrade-in-place
        # server still holding write locks) shouldn't prevent first-time
        # schema migrations from succeeding.
        conn = sqlite3.connect(self.db_path, timeout=30)
        cursor = conn.cursor()

        # WAL mode lets readers (the dashboard's IP-analysis query) proceed
        # concurrently with writers (the analyzer's batch inserts). Without
        # it, the analyzer's commit can block reads long enough to time out
        # the dashboard's fetch. journal_mode=WAL is a persistent setting on
        # the DB file; setting busy_timeout adds an extra cushion when a
        # writer is mid-commit. Both are best-effort: if the DB is locked
        # by an old server we don't want to fail startup.
        try:
            cursor.execute('PRAGMA journal_mode=WAL')
            cursor.execute('PRAGMA busy_timeout=10000')
            cursor.execute('PRAGMA synchronous=NORMAL')
        except sqlite3.OperationalError as e:
            print(f"[db] PRAGMA setup skipped: {e}")
        
        # AGENTS Table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS agents (
                node_id TEXT PRIMARY KEY,
                name TEXT,
                ip TEXT,
                last_heartbeat TEXT,
                status TEXT, -- Online, Offline
                config_json TEXT,
                is_active INTEGER DEFAULT 1, -- 1: Active, 0: Inactive
                runtime_status_json TEXT
            )
        ''')
        
        # Migration: Add is_active if it doesn't exist
        try:
            cursor.execute('ALTER TABLE agents ADD COLUMN is_active INTEGER DEFAULT 1')
        except sqlite3.OperationalError:
            pass 

        try:
            cursor.execute('ALTER TABLE agents ADD COLUMN runtime_status_json TEXT')
        except sqlite3.OperationalError:
            pass

        # Migration: Add whitelist_json if it doesn't exist
        try:
            cursor.execute('ALTER TABLE agents ADD COLUMN whitelist_json TEXT')
        except sqlite3.OperationalError:
            pass
        
        # LOGS Table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT,
                node_id TEXT,
                protocol TEXT,
                attacker_ip TEXT,
                request_data TEXT,
                response_data TEXT,
                metadata TEXT
            )
        ''')

        # WHITELIST_LOGS Table — traffic from whitelisted IPs. Kept separate
        # so it never enters the attack-log pipeline (attack map, recent
        # logs, ELK JSON dump), but is still queryable for audit.
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS whitelist_logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT,
                node_id TEXT,
                protocol TEXT,
                attacker_ip TEXT,
                request_data TEXT,
                response_data TEXT,
                metadata TEXT
            )
        ''')

        # ALERTS Table — Suricata-style alerts generated by the analyzer.
        # `source` distinguishes internal rule engine output from a real
        # Suricata eve.json import.
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS alerts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT,
                attacker_ip TEXT,
                node_id TEXT,
                protocol TEXT,
                signature TEXT,
                signature_id INTEGER,
                category TEXT,
                severity INTEGER,
                src_ip TEXT,
                src_port INTEGER,
                dst_ip TEXT,
                dst_port INTEGER,
                log_id INTEGER,
                source TEXT DEFAULT 'internal',
                metadata TEXT,
                UNIQUE(log_id, signature_id, source)
            )
        ''')
        # Index builds and historical cleanup can take a long time on a
        # production DB. Keep startup predictable by making those maintenance
        # tasks explicit instead of running them on every server boot.
        if os.environ.get("DB_MAINTENANCE_ON_STARTUP", "").lower() in ("1", "true", "yes"):
            for idx_sql in (
                'CREATE INDEX IF NOT EXISTS idx_alerts_ip ON alerts(attacker_ip)',
                'CREATE INDEX IF NOT EXISTS idx_alerts_ts ON alerts(timestamp)',
                'CREATE INDEX IF NOT EXISTS idx_alerts_ip_id ON alerts(attacker_ip, id DESC)',
                'CREATE INDEX IF NOT EXISTS idx_logs_ip ON logs(attacker_ip)',
                'CREATE INDEX IF NOT EXISTS idx_logs_ts_ip ON logs(timestamp, attacker_ip)',
            ):
                try:
                    cursor.execute(idx_sql)
                except sqlite3.OperationalError as e:
                    print(f"[db] index create skipped: {e}")

            # One-time cleanup: the legacy Suricata-style internal analyzer used
            # to bulk-insert sentinel rows (`internal-scanned`) plus its own
            # `internal` / `suricata-external` alerts. We've removed it in favor
            # of ElastAlert, so drop those rows. Idempotent — once they're gone
            # this DELETE matches zero rows.
            try:
                cursor.execute(
                    "DELETE FROM alerts WHERE source IN "
                    "('internal', 'internal-scanned', 'suricata-external')"
                )
                if cursor.rowcount:
                    print(f"[db] removed {cursor.rowcount:,} legacy analyzer alert rows")
            except sqlite3.OperationalError as e:
                print(f"[db] legacy alert cleanup skipped: {e}")

        conn.commit()
        conn.close()

    # --- Agent Management ---
    
    def _decode_agent_row(self, row):
        agent = dict(row)
        if agent.get('runtime_status_json'):
            try:
                agent['runtime_status'] = json.loads(agent['runtime_status_json'])
            except Exception:
                agent['runtime_status'] = {}
        else:
            agent['runtime_status'] = {}
        return agent

    async def register_agent(self, node_id, name="Unknown Agent", ip="0.0.0.0", config=None, runtime_status=None):
        now = datetime.now().isoformat()
        
        if config is None:
            # Default config when none provided; server_url will be updated
            # by main.py's get_server_public_url() upon first heartbeat.
            config = {
                "node_id": node_id,
                "server_url": os.environ.get("SERVER_PUBLIC_URL", "").strip() or "http://localhost:8000",
                "deployments": []
            }
        
        config_str = json.dumps(config)
        runtime_status_str = json.dumps(runtime_status or {})
        
        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                # Check if agent exists to preserve is_active/runtime status/whitelist
                async with db.execute('SELECT is_active, runtime_status_json, whitelist_json FROM agents WHERE node_id = ?', (node_id,)) as cursor:
                    row = await cursor.fetchone()
                    is_active = row[0] if row else 0 # Default to 0 (Inactive) if new agent
                    if row and row[1] and not runtime_status:
                        runtime_status_str = row[1]
                    # Preserve existing whitelist — INSERT OR REPLACE would wipe it
                    # because SQLite REPLACE = DELETE + INSERT.
                    whitelist_json = row[2] if row else None

                await db.execute('''
                    INSERT OR REPLACE INTO agents (node_id, name, ip, last_heartbeat, status, config_json, is_active, runtime_status_json, whitelist_json)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                ''', (node_id, name, ip, now, "Online", config_str, is_active, runtime_status_str, whitelist_json))
                
                await db.commit()
        return config

    async def update_heartbeat(self, node_id, ip=None, name=None, runtime_status=None):
        now = datetime.now().isoformat()
        runtime_status_str = json.dumps(runtime_status or {})
        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                cursor = await db.execute(
                    'UPDATE agents SET last_heartbeat = ?, status = ?, ip = COALESCE(?, ip), name = COALESCE(?, name), runtime_status_json = ? WHERE node_id = ?', 
                    (now, "Online", ip, name, runtime_status_str, node_id)
                )
                changes = cursor.rowcount
                await db.commit()
        return changes > 0

    async def get_agent(self, node_id):
        async with aiosqlite.connect(self.db_path, timeout=20) as db:
            db.row_factory = aiosqlite.Row
            async with db.execute('SELECT * FROM agents WHERE node_id = ?', (node_id,)) as cursor:
                row = await cursor.fetchone()
                if row:
                    return self._decode_agent_row(row)
        return None

    async def get_all_agents(self):
        async with aiosqlite.connect(self.db_path, timeout=20) as db:
            db.row_factory = aiosqlite.Row
            async with db.execute('SELECT * FROM agents ORDER BY node_id') as cursor:
                rows = await cursor.fetchall()
        
        agents = []
        for row in rows:
            agent = self._decode_agent_row(row)
            # Check timeout. Some nodes can spend a few minutes draining local
            # log backlog before their next heartbeat, so keep this tolerant
            # and configurable instead of using a hard-coded 30-second cutoff.
            try:
                last_seen = datetime.fromisoformat(agent['last_heartbeat'])
                heartbeat_age = (datetime.now() - last_seen).total_seconds()
                agent['heartbeat_age_seconds'] = int(heartbeat_age)
                if heartbeat_age > self.agent_offline_after_seconds:
                    agent['status'] = 'Offline'
            except Exception:
                pass 
            agents.append(agent)
            
        return agents
        
    async def update_agent_config(self, node_id, config_dict, name=None):
        config_str = json.dumps(config_dict)
        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                if name:
                    await db.execute('UPDATE agents SET config_json = ?, name = ? WHERE node_id = ?', (config_str, name, node_id))
                else:
                    await db.execute('UPDATE agents SET config_json = ? WHERE node_id = ?', (config_str, node_id))
                await db.commit()

    async def rename_agent(self, old_node_id, new_node_id):
        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                try:
                    # Check if new ID exists
                    async with db.execute('SELECT 1 FROM agents WHERE node_id = ?', (new_node_id,)) as cursor:
                        if await cursor.fetchone():
                            return False, "New Node ID already exists"

                    # Update agents table (whitelist_json stays with the row)
                    await db.execute('UPDATE agents SET node_id = ? WHERE node_id = ?', (new_node_id, old_node_id))
                    
                    # Update logs table
                    await db.execute('UPDATE logs SET node_id = ? WHERE node_id = ?', (new_node_id, old_node_id))

                    # Update whitelist_logs table
                    await db.execute('UPDATE whitelist_logs SET node_id = ? WHERE node_id = ?', (new_node_id, old_node_id))
                    
                    await db.commit()
                    return True, "Renamed successfully"
                except Exception as e:
                    await db.rollback()
                    return False, str(e)

    async def delete_agent(self, node_id):
        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                await db.execute('DELETE FROM logs WHERE node_id = ?', (node_id,))
                await db.execute('DELETE FROM whitelist_logs WHERE node_id = ?', (node_id,))
                await db.execute('DELETE FROM agents WHERE node_id = ?', (node_id,))
                await db.commit()

    async def toggle_agent_active(self, node_id, is_active):
        val = 1 if is_active else 0
        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                await db.execute('UPDATE agents SET is_active = ? WHERE node_id = ?', (val, node_id))
                await db.commit()

    # --- Per-Agent Whitelist ---

    async def get_agent_whitelist(self, node_id):
        async with aiosqlite.connect(self.db_path, timeout=20) as db:
            async with db.execute('SELECT whitelist_json FROM agents WHERE node_id = ?', (node_id,)) as cursor:
                row = await cursor.fetchone()
                if row and row[0]:
                    try:
                        return json.loads(row[0])
                    except (json.JSONDecodeError, TypeError):
                        pass
        return None

    async def update_agent_whitelist(self, node_id, whitelist_dict):
        whitelist_str = json.dumps(whitelist_dict, ensure_ascii=False)
        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                await db.execute('UPDATE agents SET whitelist_json = ? WHERE node_id = ?', (whitelist_str, node_id))
                await db.commit()

    # --- Log Management ---

    async def _log_to_json_file(self, log_entry):
        try:
            # Ensure log directory exists
            log_dir = os.path.join(os.path.dirname(self.db_path), "logs")
            if not os.path.exists(log_dir):
                os.makedirs(log_dir)

            # Filename by date
            date_str = datetime.now().strftime("%Y-%m-%d")
            log_file = os.path.join(log_dir, f"honeypot-{date_str}.json")

            async with aiofiles.open(log_file, "a") as f:
                await f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
        except Exception as e:
            print(f"JSON Logging Error: {e}")

    @staticmethod
    def _parse_metadata(meta):
        """Parse metadata string to dict, handling edge cases"""
        if isinstance(meta, dict):
            return meta
        if isinstance(meta, str):
            if meta in ("None", "null", ""):
                return {}
            try:
                parsed = json.loads(meta)
                return parsed if isinstance(parsed, dict) else {"raw": meta}
            except (json.JSONDecodeError, ValueError):
                return {"raw": meta}
        return {}

    @staticmethod
    def _build_elk_entry(node_id, timestamp, attacker_ip, protocol, req, resp, meta_dict):
        """
        Build a flat, ELK-friendly JSON entry.
        Dots in key names are replaced with underscores to avoid
        Elasticsearch nested object mapping conflicts.
        """
        elk = {
            "@timestamp": timestamp,
            "node_id": node_id,
            "protocol": protocol,
            "attacker_ip": attacker_ip,
            "request_data": req,
            "response_data": resp,
        }

        # Extract well-known fields from metadata
        elk["deployment_id"] = meta_dict.get("deployment.id", "")
        elk["deployment_name"] = meta_dict.get("deployment.name", "")
        elk["event_id"] = meta_dict.get("event_id", "")
        elk["session_id"] = meta_dict.get("session.id", "")
        elk["log_message"] = meta_dict.get("log.message", "")
        elk["log_source"] = meta_dict.get("source", "")

        # Extract network info from unified entry if available
        unified = meta_dict.get("_unified_entry", {})
        network = unified.get("network", {})
        if network:
            elk["src_ip"] = network.get("src_ip", attacker_ip)
            elk["src_port"] = network.get("src_port", 0)
            elk["dst_ip"] = network.get("dst_ip", "")
            elk["dst_port"] = network.get("dst_port", 0)

        session = unified.get("session", {})
        if session:
            elk["session_request_count"] = session.get("request_count", 0)
            elk["session_duration_ms"] = session.get("duration_ms", 0)

        req_size = unified.get("request", {}).get("size_bytes", 0)
        resp_size = unified.get("response", {}).get("size_bytes", 0)
        if req_size:
            elk["request_size_bytes"] = req_size
        if resp_size:
            elk["response_size_bytes"] = resp_size

        # Flatten protocol-specific parsed fields (replace dots with underscores)
        skip_keys = {
            "deployment.id", "deployment.name", "event_id", "session.id",
            "log.message", "source", "_unified_entry", "valid", "raw_length",
            "log.file",
        }
        for key, value in meta_dict.items():
            if key in skip_keys:
                continue
            # Replace dots with underscores for ELK compatibility
            elk_key = key.replace(".", "_")
            if elk_key not in elk:
                elk[elk_key] = value

        return elk

    async def insert_logs(self, node_id, logs):
        rows = []
        for log in logs:
            # log dict structure from client: {timestamp, attacker_ip, protocol, request_data, response_data, metadata}
            timestamp = log.get('timestamp') or datetime.now().isoformat()
            attacker_ip = log.get('attacker_ip')
            protocol = log.get('protocol')
            req = log.get('request_data')
            resp = log.get('response_data')
            meta = log.get('metadata')

            meta_dict = self._parse_metadata(meta)
            elk_entry = self._build_elk_entry(
                node_id, timestamp, attacker_ip, protocol, req, resp, meta_dict
            )
            await self._log_to_json_file(elk_entry)

            meta_str = json.dumps(meta_dict, ensure_ascii=False) if isinstance(meta_dict, dict) else str(meta_dict)
            if isinstance(req, (dict, list)): req = json.dumps(req)
            if isinstance(resp, (dict, list)): resp = json.dumps(resp)
            rows.append((timestamp, node_id, protocol, attacker_ip, req, resp, meta_str))

        if not rows:
            return 0

        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                await db.executemany('''
                    INSERT INTO logs (timestamp, node_id, protocol, attacker_ip, request_data, response_data, metadata)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                ''', rows)

                await db.commit()
        return len(rows)

    async def get_recent_logs(self, limit=100):
        async with aiosqlite.connect(self.db_path, timeout=20) as db:
            db.row_factory = aiosqlite.Row
            if limit is None:
                cursor_ctx = db.execute('SELECT * FROM logs ORDER BY id DESC')
            else:
                cursor_ctx = db.execute('SELECT * FROM logs ORDER BY id DESC LIMIT ?', (limit,))
            async with cursor_ctx as cursor:
                rows = await cursor.fetchall()
        return [dict(row) for row in rows]

    async def delete_agent_logs(self, node_id):
        """Delete all logs for a specific agent"""
        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                await db.execute('DELETE FROM logs WHERE node_id = ?', (node_id,))
                await db.commit()

    # ---------- Whitelist log methods ----------

    async def insert_whitelist_logs(self, node_id, logs):
        """Insert friendly traffic into whitelist_logs.

        Mirrors insert_logs() but writes to whitelist_logs instead and
        intentionally does NOT call _log_to_json_file() — whitelist entries
        must not appear in the ELK ingest stream.
        """
        rows = []
        for log in logs:
            timestamp = log.get('timestamp') or datetime.now().isoformat()
            attacker_ip = log.get('attacker_ip')
            protocol = log.get('protocol')
            req = log.get('request_data')
            resp = log.get('response_data')
            meta = log.get('metadata')

            meta_dict = self._parse_metadata(meta)
            meta_str = json.dumps(meta_dict, ensure_ascii=False) if isinstance(meta_dict, dict) else str(meta_dict)
            if isinstance(req, (dict, list)): req = json.dumps(req)
            if isinstance(resp, (dict, list)): resp = json.dumps(resp)
            rows.append((timestamp, node_id, protocol, attacker_ip, req, resp, meta_str))

        if not rows:
            return 0

        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                await db.executemany('''
                    INSERT INTO whitelist_logs (timestamp, node_id, protocol, attacker_ip, request_data, response_data, metadata)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                ''', rows)

                await db.commit()
        return len(rows)

    async def get_recent_whitelist_logs(self, limit=100, node_id=None):
        async with aiosqlite.connect(self.db_path, timeout=20) as db:
            db.row_factory = aiosqlite.Row
            if node_id:
                query = 'SELECT * FROM whitelist_logs WHERE node_id = ? ORDER BY id DESC LIMIT ?'
                params = (node_id, limit)
            else:
                query = 'SELECT * FROM whitelist_logs ORDER BY id DESC LIMIT ?'
                params = (limit,)
            async with db.execute(query, params) as cursor:
                rows = await cursor.fetchall()
        return [dict(row) for row in rows]

    async def delete_agent_whitelist_logs(self, node_id):
        """Delete all whitelist logs for a specific agent"""
        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                await db.execute('DELETE FROM whitelist_logs WHERE node_id = ?', (node_id,))
                await db.commit()

    # ---------- IP analysis (used by attack-map analysis panel) ----------

    async def get_ip_summary(self, limit=200, since=None, until=None, offset=0, ip_search=None, exclude_ips=None, hide_private_ips=False):
        """Return per-attacker-IP rollups joined with alert stats.

        Each row: ip, total_packets, protocols (csv), node_ids (csv),
        first_seen, last_seen, alert_count, max_severity.

        ``since`` / ``until`` are ISO timestamp strings; either or both may
        be supplied. The alert sub-queries honor the same window so the
        ``alert_count`` / ``max_severity`` columns match what the user is
        actually viewing.
        """
        private_ip_patterns = (
            ["10.%", "127.%", "169.254.%", "192.168.%", "0.%"]
            + [f"172.{i}.%" for i in range(16, 32)]
            + ["fc%", "fd%"]
        )

        def add_not_private_filter(clauses: list, target_params: list, column: str):
            clauses.append(
                "("
                + " AND ".join(f"{column} NOT LIKE ?" for _ in private_ip_patterns)
                + f" AND {column} != ?"
                + ")"
            )
            target_params.extend(private_ip_patterns)
            target_params.append("::1")

        where_clauses: list = []
        params: list = []
        if since:
            where_clauses.append("l.timestamp >= ?")
            params.append(since)
        if until:
            where_clauses.append("l.timestamp <= ?")
            params.append(until)
        if ip_search:
            where_clauses.append("l.attacker_ip LIKE ?")
            params.append(f"%{ip_search}%")
        exclude_ips = [ip for ip in (exclude_ips or []) if ip]
        if exclude_ips:
            where_clauses.append(
                "l.attacker_ip NOT IN (" + ",".join("?" for _ in exclude_ips) + ")"
            )
            params.extend(exclude_ips)
        if hide_private_ips:
            add_not_private_filter(where_clauses, params, "l.attacker_ip")
        where = (" AND " + " AND ".join(where_clauses)) if where_clauses else ""

        # Alert sub-queries need their own window predicates because they
        # reference the alerts table, not logs.
        alert_where = []
        alert_params: list = []
        if since:
            alert_where.append("a.timestamp >= ?")
            alert_params.append(since)
        if until:
            alert_where.append("a.timestamp <= ?")
            alert_params.append(until)
        if ip_search:
            alert_where.append("a.attacker_ip LIKE ?")
            alert_params.append(f"%{ip_search}%")
        if exclude_ips:
            alert_where.append(
                "a.attacker_ip NOT IN (" + ",".join("?" for _ in exclude_ips) + ")"
            )
            alert_params.extend(exclude_ips)
        if hide_private_ips:
            add_not_private_filter(alert_where, alert_params, "a.attacker_ip")
        # The logs table can be multiple GB because metadata stores full
        # packet context. Keep this dashboard query bounded even when a time
        # window is selected; otherwise the default "Last 7 days" view can
        # spend many seconds grouping millions of rows and appear blank.
        main_where = list(where_clauses)
        main_params = list(params)
        scan_limit = int(os.environ.get("IP_ANALYSIS_SCAN_ROWS", "2000"))
        scan_limit = max(min(scan_limit, 250000), 1000)
        main_where.append("l.id >= COALESCE((SELECT MAX(id) FROM logs), 0) - ?")
        main_params.append(scan_limit)
        main_where.append("l.attacker_ip IS NOT NULL")
        main_where.append("l.attacker_ip != ''")
        where = ("WHERE " + " AND ".join(main_where)) if main_where else ""

        alert_scan_limit = int(os.environ.get("IP_ANALYSIS_ALERT_SCAN_ROWS", "10000"))
        alert_scan_limit = max(min(alert_scan_limit, 250000), 1000)
        alert_where.append("a.id >= COALESCE((SELECT MAX(id) FROM alerts), 0) - ?")
        alert_params.append(alert_scan_limit)
        alert_where.append("a.attacker_ip IS NOT NULL")
        alert_where.append("a.attacker_ip != ''")
        alert_summary_where = ("WHERE " + " AND ".join(alert_where)) if alert_where else ""

        sql = f'''
            WITH log_summary AS (
                SELECT
                    l.attacker_ip AS ip,
                    COUNT(*) AS total_packets,
                    GROUP_CONCAT(DISTINCT l.protocol) AS protocols,
                    GROUP_CONCAT(DISTINCT l.node_id) AS node_ids,
                    MIN(l.timestamp) AS first_seen,
                    MAX(l.timestamp) AS last_seen
                FROM logs l NOT INDEXED
                {where}
                GROUP BY l.attacker_ip
            ),
            alert_summary AS (
                SELECT
                    a.attacker_ip AS ip,
                    COUNT(*) AS alert_count,
                    MIN(a.severity) AS max_severity
                FROM alerts a
                {alert_summary_where}
                GROUP BY a.attacker_ip
            )
            SELECT
                ls.ip,
                ls.total_packets,
                ls.protocols,
                ls.node_ids,
                ls.first_seen,
                ls.last_seen,
                COALESCE(a.alert_count, 0) AS alert_count,
                COALESCE(a.max_severity, 0) AS max_severity
            FROM log_summary ls
            LEFT JOIN alert_summary a ON a.ip = ls.ip
            ORDER BY ls.last_seen DESC
            LIMIT ?
        '''
        params = main_params + alert_params
        params.append(limit)

        db_uri = f"file:{self.db_path}?mode=ro"
        conn = sqlite3.connect(db_uri, uri=True, timeout=2)
        conn.row_factory = sqlite3.Row
        try:
            conn.execute("PRAGMA busy_timeout=2000")
            deadline = time.monotonic() + float(
                os.environ.get("IP_ANALYSIS_QUERY_TIMEOUT_SECONDS", "5")
            )
            conn.set_progress_handler(
                lambda: 1 if time.monotonic() > deadline else 0,
                1000,
            )
            cursor = conn.execute(sql, params)
            return [dict(r) for r in cursor.fetchall()]
        finally:
            conn.set_progress_handler(None, 0)
            conn.close()

    async def get_logs_by_ip(self, ip, limit=200):
        async with aiosqlite.connect(self.db_path, timeout=20) as db:
            db.row_factory = aiosqlite.Row
            async with db.execute(
                'SELECT * FROM logs WHERE attacker_ip = ? ORDER BY id DESC LIMIT ?',
                (ip, limit),
            ) as cursor:
                rows = await cursor.fetchall()
        return [dict(r) for r in rows]

    # ---------- Alerts ----------

    async def insert_alert(self, alert: dict) -> bool:
        """Insert one alert. Returns True if newly inserted, False if duplicate."""
        async with self._write_lock:
            async with aiosqlite.connect(self.db_path, timeout=30) as db:
                await db.execute('PRAGMA busy_timeout=30000')
                try:
                    await db.execute(
                        '''INSERT OR IGNORE INTO alerts
                           (timestamp, attacker_ip, node_id, protocol, signature, signature_id,
                            category, severity, src_ip, src_port, dst_ip, dst_port, log_id, source, metadata)
                           VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',
                        (
                            alert.get("timestamp") or datetime.now().isoformat(),
                            alert.get("attacker_ip"),
                            alert.get("node_id"),
                            alert.get("protocol"),
                            alert.get("signature"),
                            alert.get("signature_id"),
                            alert.get("category"),
                            alert.get("severity") or 3,
                            alert.get("src_ip"),
                            alert.get("src_port") or 0,
                            alert.get("dst_ip"),
                            alert.get("dst_port") or 0,
                            alert.get("log_id"),
                            alert.get("source") or "internal",
                            json.dumps(alert.get("metadata") or {}, ensure_ascii=False),
                        ),
                    )
                    changes = db.total_changes
                    await db.commit()
                    return changes > 0
                except Exception as e:
                    print(f"insert_alert error: {e}")
                    return False

    async def get_alerts(self, limit=200, ip=None):
        async with aiosqlite.connect(self.db_path, timeout=20) as db:
            db.row_factory = aiosqlite.Row
            if ip:
                sql = 'SELECT * FROM alerts WHERE attacker_ip = ? ORDER BY id DESC LIMIT ?'
                params = (ip, limit)
            else:
                sql = 'SELECT * FROM alerts ORDER BY id DESC LIMIT ?'
                params = (limit,)
            async with db.execute(sql, params) as cursor:
                rows = await cursor.fetchall()
        return [dict(r) for r in rows]
